In [1]:
import torch

In [3]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.4900, 0.3988, 0.6537, 0.0961],
         [0.0090, 0.3490, 0.0111, 0.5158],
         [0.6907, 0.3089, 0.2702, 0.9770]]),
 torch.float32,
 torch.Size([3, 4]))

In [4]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [5]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [6]:
# Use torch.arange() for range of values - 0 to 10
zero_to_ten_deprecated = torch.arange(0, 10)
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Sometimes you might want one tensor of a certain type with the same shape as another tensor.
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
#An integer is a flat round number like 7 whereas a float has a decimal 7.0
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device="cpu", # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [12]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [13]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# what, what, where
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8289, 0.0508, 0.6919, 0.1957],
        [0.1210, 0.1900, 0.9974, 0.3138],
        [0.1793, 0.5732, 0.5443, 0.4348]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Manipulating tensors (tensor operations)**

In [14]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [15]:
tensor * 10

tensor([10, 20, 30])

In [16]:
print("Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned")

Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned


In [17]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [18]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [19]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
