In [1]:
import torch
torch.__version__

'2.6.0+cu124'

In [16]:
# A scalar is a single number and in tensor-speak it's a zero dimension tensor.
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [17]:
#dimensions
print(scalar.ndim)

0


In [18]:
# Get the Python number within a tensor
print(scalar.item())

7


In [19]:
# Vector, 1-dimensional tensor called a vector.
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [10]:
#  shape tells you how the elements inside them are arranged
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [20]:
# matrix, a 2-dimensional tensor is often referred to as a matrix.
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [13]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [14]:
# Tensor, Anything with more than two dimensions is generally just called a tensor.
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])
